// <auto-generated />
using System;
using Infraestructure.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(ContextBase))]
    [Migration("20231006192849_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Entities.AreaComum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<int>("Id_condominio")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("Limite")
                        .HasColumnType("int")
                        .HasColumnName("Limite");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.HasIndex("Id_condominio");

                    b.ToTable("AreaComum");
                });

            modelBuilder.Entity("Domain.Entities.Arquivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Classificacao");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataUpload");

                    b.Property<int>("Id_condominio")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("TamanhoArquivo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TamanhoArquivo");

                    b.HasKey("Id");

                    b.HasIndex("Id_condominio");

                    b.ToTable("Arquivo");
                });

            modelBuilder.Entity("Domain.Entities.Condominio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Bairro");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CEP");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Cidade");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Estado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.Property<int>("Numero")
                        .HasColumnType("int")
                        .HasColumnName("Numero");

                    b.Property<bool>("Porteiro")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Porteiro");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Rua");

                    b.HasKey("Id");

                    b.ToTable("Condominio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bairro = "Bairro Morus",
                            CEP = "29101000",
                            Cidade = "Vila Velha",
                            Estado = "ES",
                            Nome = "Condominio Morus",
                            Numero = 1,
                            Porteiro = false,
                            Rua = "Rua Morus"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Informacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Ativo");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataCadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Descricao");

                    b.Property<int>("Id_condominio")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Titulo");

                    b.HasKey("Id");

                    b.HasIndex("Id_condominio");

                    b.ToTable("Informacao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataAlteracao = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descrição de informação inicial teste, lorem ipsum",
                            Id_condominio = 1,
                            Titulo = "Informação inicial"
                        });
                });

            modelBuilder.Entity("Domain.Entities.LivroCaixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Categoria");

                    b.Property<DateTime>("DataTransacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataTransacao");

                    b.Property<string>("DescricaoTransacao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DescricaoTransacao");

                    b.Property<int>("Id_condominio")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NumeroConta");

                    b.Property<string>("Torre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Torre");

                    b.Property<decimal>("ValorTransacao")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorTransacao");

                    b.HasKey("Id");

                    b.HasIndex("Id_condominio");

                    b.ToTable("LivroCaixa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "teste",
                            DataTransacao = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescricaoTransacao = "Descrição teste",
                            Id_condominio = 1,
                            NumeroConta = "123",
                            Torre = "A",
                            ValorTransacao = 500.00m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Ativo");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataCadastro");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Titulo");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Mensagem");
                });

            modelBuilder.Entity("Domain.Entities.Multa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<DateTime>("AplicadaEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("AplicadaEm");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataExpiracao");

                    b.Property<int>("Id_usuario")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Motivo");

                    b.Property<double>("TaxaJurosDia")
                        .HasColumnType("double")
                        .HasColumnName("TaxaJurosDia");

                    b.Property<decimal>("ValorMulta")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorMulta");

                    b.HasKey("Id");

                    b.HasIndex("Id_usuario");

                    b.ToTable("Multa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AplicadaEm = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataExpiracao = new DateTime(2023, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_usuario = 2,
                            Motivo = "Jogou ovo da janela",
                            TaxaJurosDia = 1.0,
                            ValorMulta = 280.75m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ocorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_ocorrencia");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Descricao");

                    b.Property<int>("Id_usuario")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Titulo");

                    b.HasKey("Id");

                    b.HasIndex("Id_usuario");

                    b.ToTable("Ocorrencia");
                });

            modelBuilder.Entity("Domain.Entities.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataReserva");

                    b.Property<int>("Id_AreaComum")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("Id_AreaComum");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("Domain.Entities.TaxaMensal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataFim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataInicio");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Descricao");

                    b.Property<int>("Id_condominio")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.Property<bool>("Recorrente")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Recorrente");

                    b.Property<double>("Valor")
                        .HasColumnType("double")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.HasIndex("Id_condominio");

                    b.ToTable("TaxaMensal");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8df23972-8367-4223-891f-a2536b73a32d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6f045bbf-fddb-4e17-9c7f-b2cc16c6dc77",
                            Email = "sindico@sindico.com.br",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SINDICO@SINDICO.COM.BR",
                            NormalizedUserName = "SINDICO@SINDICO.COM.BR",
                            PasswordHash = "AQAAAAEAACcQAAAAEIswx0rGRNhPcKmRzpn7o0i3+oW1pIMl6cf9wd+S3WInfuFPYSrE2EwsIDTEnN/W7g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e7f55a8a-8ed4-4b49-805d-c3d368b61e80",
                            TwoFactorEnabled = false,
                            UserName = "sindico@sindico.com.br"
                        },
                        new
                        {
                            Id = "ebafef68-4f09-4fc5-834c-2b0871b770c0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4c34c2d1-b91d-461c-a855-0f3792140eb3",
                            Email = "morador@morador.com.br",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MORADOR@MORADOR.COM.BR",
                            NormalizedUserName = "MORADOR@MORADOR.COM.BR",
                            PasswordHash = "AQAAAAEAACcQAAAAEFCbu5TQX0ZVwT8joHu4IzzW0RwjvtYvMRUGM55ZXRwsu2SFCf42Xr00Cqpd2lgOEA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a7161f8a-e2ec-4d0d-a188-bfde5beeaf03",
                            TwoFactorEnabled = false,
                            UserName = "morador@morador.com.br"
                        },
                        new
                        {
                            Id = "6d0ba1ee-344d-4827-ae35-f95f8df993cd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c302283f-974b-40d7-9231-4b7c72a01108",
                            Email = "admin@admin.com.br",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM.BR",
                            NormalizedUserName = "ADMIN@ADMIN.COM.BR",
                            PasswordHash = "AQAAAAEAACcQAAAAEJsb6Mt9G/IPEDHzSsOlXGyGcLwdkWfCd5SpqEUDkvHnr/atIaFxP/IC1ZC1SRaKUQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "00cef1ef-157f-49a8-ba41-d8de94364ceb",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com.br"
                        },
                        new
                        {
                            Id = "69a5fe94-1d42-48dd-ab10-8f97a3b2140f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "20482492-a783-4d71-a8ff-a272c2447bbb",
                            Email = "porteiro@porteiro.com.br",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "PORTEIRO@PORTEIRO.COM.BR",
                            NormalizedUserName = "PORTEIRO@PORTEIRO.COM.BR",
                            PasswordHash = "AQAAAAEAACcQAAAAEI9FSXy6GsFGnxCQMT86LRP+SwXqjmX5z0opRXAHctRNdQX1ihXKgEkqMRsm40GwIA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "73c1a8bd-d4b4-4134-83a3-97e114681207",
                            TwoFactorEnabled = false,
                            UserName = "porteiro@porteiro.com.br"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<int?>("Apartamento")
                        .HasColumnType("int")
                        .HasColumnName("Apartamento");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CPF");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataNascimento");

                    b.Property<string>("IdUserIdentity")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Id_condominio")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.Property<string>("Torre")
                        .HasColumnType("longtext")
                        .HasColumnName("Torre");

                    b.HasKey("Id");

                    b.HasIndex("IdUserIdentity");

                    b.HasIndex("Id_condominio");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apartamento = 1,
                            CPF = "12345678999",
                            DataNascimento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdUserIdentity = "8df23972-8367-4223-891f-a2536b73a32d",
                            Id_condominio = 1,
                            Nome = "Sindico da Costa Filho",
                            Torre = "A"
                        },
                        new
                        {
                            Id = 2,
                            Apartamento = 2,
                            CPF = "12343223444",
                            DataNascimento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdUserIdentity = "ebafef68-4f09-4fc5-834c-2b0871b770c0",
                            Id_condominio = 1,
                            Nome = "Morador de Carvalho",
                            Torre = "A"
                        },
                        new
                        {
                            Id = 3,
                            Apartamento = 3,
                            CPF = "12343223445",
                            DataNascimento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdUserIdentity = "69a5fe94-1d42-48dd-ab10-8f97a3b2140f",
                            Id_condominio = 1,
                            Nome = "Porteiro Fernandes",
                            Torre = "A"
                        },
                        new
                        {
                            Id = 4,
                            Apartamento = 3,
                            CPF = "12343223456",
                            DataNascimento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdUserIdentity = "6d0ba1ee-344d-4827-ae35-f95f8df993cd",
                            Id_condominio = 1,
                            Nome = "Administrador",
                            Torre = "A"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Votacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataCriacao");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataExpiracao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Descricao");

                    b.Property<int>("Id_condominio")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Tema");

                    b.HasKey("Id");

                    b.HasIndex("Id_condominio");

                    b.ToTable("Votacao");
                });

            modelBuilder.Entity("Domain.Entities.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<int>("Id_usuario")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<int>("Id_votacao")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("ValorVoto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_usuario");

                    b.HasIndex("Id_votacao");

                    b.ToTable("Voto");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "80ffcf89-c78b-4c3f-80a1-5c6af4567a86",
                            ConcurrencyStamp = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "b6daee1d-a9a1-4c23-9d71-d3a92fceabea",
                            ConcurrencyStamp = "2",
                            Name = "Sindico",
                            NormalizedName = "SINDICO"
                        },
                        new
                        {
                            Id = "9b9f90d6-25f8-4121-a2dd-0120e8c39a18",
                            ConcurrencyStamp = "3",
                            Name = "Morador",
                            NormalizedName = "MORADOR"
                        },
                        new
                        {
                            Id = "0cbae1b7-daa8-420e-9e19-aea2bf9784b2",
                            ConcurrencyStamp = "4",
                            Name = "Porteiro",
                            NormalizedName = "PORTEIRO"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8df23972-8367-4223-891f-a2536b73a32d",
                            RoleId = "b6daee1d-a9a1-4c23-9d71-d3a92fceabea"
                        },
                        new
                        {
                            UserId = "6d0ba1ee-344d-4827-ae35-f95f8df993cd",
                            RoleId = "80ffcf89-c78b-4c3f-80a1-5c6af4567a86"
                        },
                        new
                        {
                            UserId = "ebafef68-4f09-4fc5-834c-2b0871b770c0",
                            RoleId = "9b9f90d6-25f8-4121-a2dd-0120e8c39a18"
                        },
                        new
                        {
                            UserId = "69a5fe94-1d42-48dd-ab10-8f97a3b2140f",
                            RoleId = "0cbae1b7-daa8-420e-9e19-aea2bf9784b2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AreaComum", b =>
                {
                    b.HasOne("Domain.Entities.Condominio", "Condominio")
                        .WithMany()
                        .HasForeignKey("Id_condominio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("Domain.Entities.Arquivo", b =>
                {
                    b.HasOne("Domain.Entities.Condominio", "Condominio")
                        .WithMany()
                        .HasForeignKey("Id_condominio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("Domain.Entities.Informacao", b =>
                {
                    b.HasOne("Domain.Entities.Condominio", "Condominio")
                        .WithMany()
                        .HasForeignKey("Id_condominio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("Domain.Entities.LivroCaixa", b =>
                {
                    b.HasOne("Domain.Entities.Condominio", "Condominio")
                        .WithMany()
                        .HasForeignKey("Id_condominio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("Domain.Entities.Message", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Multa", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Ocorrencia", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Reserva", b =>
                {
                    b.HasOne("Domain.Entities.AreaComum", "AreaComum")
                        .WithMany()
                        .HasForeignKey("Id_AreaComum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaComum");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.TaxaMensal", b =>
                {
                    b.HasOne("Domain.Entities.Condominio", "Condominio")
                        .WithMany()
                        .HasForeignKey("Id_condominio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUserIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Condominio", "Condominio")
                        .WithMany()
                        .HasForeignKey("Id_condominio");

                    b.Navigation("Condominio");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Votacao", b =>
                {
                    b.HasOne("Domain.Entities.Condominio", "Condominio")
                        .WithMany()
                        .HasForeignKey("Id_condominio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("Domain.Entities.Voto", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Votacao", "Votacao")
                        .WithMany()
                        .HasForeignKey("Id_votacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Votacao");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
