// <auto-generated />
using System;
using Infraestructure.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(ContextBase))]
    partial class ContextBaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Entities.AreaComum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<int>("Id_condominio")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("Limite")
                        .HasColumnType("int")
                        .HasColumnName("Limite");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.HasIndex("Id_condominio");

                    b.ToTable("AreaComum");
                });

            modelBuilder.Entity("Domain.Entities.Arquivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Classificacao");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataUpload");

                    b.Property<int>("Id_condominio")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("TamanhoArquivo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TamanhoArquivo");

                    b.HasKey("Id");

                    b.HasIndex("Id_condominio");

                    b.ToTable("Arquivo");
                });

            modelBuilder.Entity("Domain.Entities.Condominio", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Bairro");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CEP");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Cidade");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Estado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.Property<int>("Numero")
                        .HasColumnType("int")
                        .HasColumnName("Numero");

                    b.Property<bool>("Porteiro")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Porteiro");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Rua");

                    b.HasKey("Id");

                    b.ToTable("Condominio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bairro = "Bairro Morus",
                            CEP = "29101000",
                            Cidade = "Vila Velha",
                            Estado = "ES",
                            Nome = "Condominio Morus",
                            Numero = 1,
                            Porteiro = false,
                            Rua = "Rua Morus"
                        },
                        new
                        {
                            Id = 2,
                            Bairro = "Bairro",
                            CEP = "29101001",
                            Cidade = "Vila Velha",
                            Estado = "ES",
                            Nome = "Condominio Dois",
                            Numero = 2,
                            Porteiro = false,
                            Rua = "Rua Dois"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Informacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Ativo");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataCadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Descricao");

                    b.Property<int>("Id_condominio")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Titulo");

                    b.HasKey("Id");

                    b.HasIndex("Id_condominio");

                    b.ToTable("Informacao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataAlteracao = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCadastro = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descrição de informação inicial teste, lorem ipsum",
                            Id_condominio = 1,
                            Titulo = "Informação inicial"
                        });
                });

            modelBuilder.Entity("Domain.Entities.LivroCaixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Categoria");

                    b.Property<DateTime>("DataTransacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataTransacao");

                    b.Property<string>("DescricaoTransacao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DescricaoTransacao");

                    b.Property<int>("Id_condominio")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NumeroConta");

                    b.Property<string>("Torre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Torre");

                    b.Property<decimal>("ValorTransacao")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorTransacao");

                    b.HasKey("Id");

                    b.HasIndex("Id_condominio");

                    b.ToTable("LivroCaixa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "teste",
                            DataTransacao = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescricaoTransacao = "Descrição teste",
                            Id_condominio = 1,
                            NumeroConta = "123",
                            Torre = "A",
                            ValorTransacao = 500.00m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Ativo");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataCadastro");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Titulo");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Mensagem");
                });

            modelBuilder.Entity("Domain.Entities.Multa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<DateTime>("AplicadaEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("AplicadaEm");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataExpiracao");

                    b.Property<int>("Id_usuario")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Motivo");

                    b.Property<double>("TaxaJurosDia")
                        .HasColumnType("double")
                        .HasColumnName("TaxaJurosDia");

                    b.Property<decimal>("ValorMulta")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorMulta");

                    b.HasKey("Id");

                    b.HasIndex("Id_usuario");

                    b.ToTable("Multa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AplicadaEm = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataExpiracao = new DateTime(2023, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_usuario = 2,
                            Motivo = "Jogou ovo da janela",
                            TaxaJurosDia = 1.0,
                            ValorMulta = 280.75m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ocorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_ocorrencia");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Descricao");

                    b.Property<int>("Id_usuario")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Titulo");

                    b.HasKey("Id");

                    b.HasIndex("Id_usuario");

                    b.ToTable("Ocorrencia");
                });

            modelBuilder.Entity("Domain.Entities.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataReserva");

                    b.Property<int>("Id_AreaComum")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("Id_AreaComum");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("Domain.Entities.TaxaMensal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataFim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataInicio");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Descricao");

                    b.Property<int>("Id_condominio")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.Property<bool>("Recorrente")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Recorrente");

                    b.Property<double>("Valor")
                        .HasColumnType("double")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.HasIndex("Id_condominio");

                    b.ToTable("TaxaMensal");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b07436b8-86c9-4643-b28e-de59545cdd37",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aae191b2-7657-4c70-9406-6db07049bfde",
                            Email = "sindico@sindico.com.br",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SINDICO@SINDICO.COM.BR",
                            NormalizedUserName = "SINDICO@SINDICO.COM.BR",
                            PasswordHash = "AQAAAAEAACcQAAAAEAcEQUNgBtcvSDfupJGl3kxp79KZYt8Hc8Z2v5oQjDnk+AklZtG/vXZp3ouNBF3EFQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c47ff527-50c0-478b-a41c-b4a8c844137f",
                            TwoFactorEnabled = false,
                            UserName = "sindico@sindico.com.br"
                        },
                        new
                        {
                            Id = "78ca8ad7-a97b-4903-bc53-2a0a74aacc85",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2ef4e686-f353-49ab-8614-8b584d8335ef",
                            Email = "sindicoDois@sindicoDois.com.br",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SINDICODOIS@SINDICODOIS.COM.BR",
                            NormalizedUserName = "SINDICODOIS@SINDICODOIS.COM.BR",
                            PasswordHash = "AQAAAAEAACcQAAAAEAMLOzODp065SSUixvJxi4D3+nqGN+b0TZiANkGZmerA+We4chpB5zNfgzdxVT51tw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b6025b87-69c7-4a46-8839-b58a87690f14",
                            TwoFactorEnabled = false,
                            UserName = "sindicoDois@sindicoDois.com.br"
                        },
                        new
                        {
                            Id = "19704583-085c-46ca-89d1-e2220124943e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "224104e0-ab7a-4a4b-80eb-7d0c8da6316d",
                            Email = "morador@morador.com.br",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MORADOR@MORADOR.COM.BR",
                            NormalizedUserName = "MORADOR@MORADOR.COM.BR",
                            PasswordHash = "AQAAAAEAACcQAAAAEH6wfAibN5pnuIDhIXBoufe3kGCo/o1lRC/H1QXYjhdZJsQ3V2V5wn6AZFXdUpuuvQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "77bd5568-3e6e-4a05-a4a5-6c03993b0165",
                            TwoFactorEnabled = false,
                            UserName = "morador@morador.com.br"
                        },
                        new
                        {
                            Id = "1195fdac-ce79-4679-9ef8-5a90bf4386cb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9cb26c4e-2193-4c0a-bc52-8cce627eb726",
                            Email = "admin@admin.com.br",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM.BR",
                            NormalizedUserName = "ADMIN@ADMIN.COM.BR",
                            PasswordHash = "AQAAAAEAACcQAAAAEIagOFhndid+soJUypG38O847cKDT2jaLfaRX8iUlP3kopz+8uCpBh8yvGSWIKGf4A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1becb01f-5c34-4236-b0a6-eeeb4d113394",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com.br"
                        },
                        new
                        {
                            Id = "1871ad67-2d8a-4aff-86e6-02deedfbbdde",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ae7ec015-d7e8-4408-acef-008c8eed9ea2",
                            Email = "porteiro@porteiro.com.br",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "PORTEIRO@PORTEIRO.COM.BR",
                            NormalizedUserName = "PORTEIRO@PORTEIRO.COM.BR",
                            PasswordHash = "AQAAAAEAACcQAAAAEB/sSfHhCaanJJ/1ytJITlF986nN/I2XTqSXMpfT9DEpl1C4EL1EvZwFOc5KmhMCVQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a50b89bc-aedf-449a-9e35-09f5c6fafbc6",
                            TwoFactorEnabled = false,
                            UserName = "porteiro@porteiro.com.br"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<int?>("Apartamento")
                        .HasColumnType("int")
                        .HasColumnName("Apartamento");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CPF");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataNascimento");

                    b.Property<string>("IdUserIdentity")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Id_condominio")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.Property<string>("Torre")
                        .HasColumnType("longtext")
                        .HasColumnName("Torre");

                    b.HasKey("Id");

                    b.HasIndex("IdUserIdentity");

                    b.HasIndex("Id_condominio");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apartamento = 1,
                            CPF = "12345678999",
                            DataNascimento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdUserIdentity = "b07436b8-86c9-4643-b28e-de59545cdd37",
                            Id_condominio = 1,
                            Nome = "Sindico da Costa Filho",
                            Torre = "A"
                        },
                        new
                        {
                            Id = 2,
                            Apartamento = 2,
                            CPF = "12343223444",
                            DataNascimento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdUserIdentity = "19704583-085c-46ca-89d1-e2220124943e",
                            Id_condominio = 1,
                            Nome = "Morador de Carvalho",
                            Torre = "A"
                        },
                        new
                        {
                            Id = 3,
                            Apartamento = 3,
                            CPF = "12343223445",
                            DataNascimento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdUserIdentity = "1871ad67-2d8a-4aff-86e6-02deedfbbdde",
                            Id_condominio = 1,
                            Nome = "Porteiro Fernandes",
                            Torre = "A"
                        },
                        new
                        {
                            Id = 4,
                            Apartamento = 3,
                            CPF = "12343223456",
                            DataNascimento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdUserIdentity = "1195fdac-ce79-4679-9ef8-5a90bf4386cb",
                            Id_condominio = 1,
                            Nome = "Administrador",
                            Torre = "A"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Votacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataCriacao");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataExpiracao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Descricao");

                    b.Property<int>("Id_condominio")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Tema");

                    b.HasKey("Id");

                    b.HasIndex("Id_condominio");

                    b.ToTable("Votacao");
                });

            modelBuilder.Entity("Domain.Entities.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<int>("Id_usuario")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<int>("Id_votacao")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("ValorVoto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_usuario");

                    b.HasIndex("Id_votacao");

                    b.ToTable("Voto");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "05918a12-0b00-41e3-b282-d84ab714c5f5",
                            ConcurrencyStamp = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "f4d1693b-f41d-4385-a10f-e276efb1a0b5",
                            ConcurrencyStamp = "2",
                            Name = "Sindico",
                            NormalizedName = "SINDICO"
                        },
                        new
                        {
                            Id = "32d17df7-9c07-4685-872b-35b043144595",
                            ConcurrencyStamp = "3",
                            Name = "Morador",
                            NormalizedName = "MORADOR"
                        },
                        new
                        {
                            Id = "2791db68-4a17-4e4d-b192-6b61bd8b74ca",
                            ConcurrencyStamp = "4",
                            Name = "Porteiro",
                            NormalizedName = "PORTEIRO"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "b07436b8-86c9-4643-b28e-de59545cdd37",
                            RoleId = "f4d1693b-f41d-4385-a10f-e276efb1a0b5"
                        },
                        new
                        {
                            UserId = "78ca8ad7-a97b-4903-bc53-2a0a74aacc85",
                            RoleId = "f4d1693b-f41d-4385-a10f-e276efb1a0b5"
                        },
                        new
                        {
                            UserId = "1195fdac-ce79-4679-9ef8-5a90bf4386cb",
                            RoleId = "05918a12-0b00-41e3-b282-d84ab714c5f5"
                        },
                        new
                        {
                            UserId = "19704583-085c-46ca-89d1-e2220124943e",
                            RoleId = "32d17df7-9c07-4685-872b-35b043144595"
                        },
                        new
                        {
                            UserId = "1871ad67-2d8a-4aff-86e6-02deedfbbdde",
                            RoleId = "2791db68-4a17-4e4d-b192-6b61bd8b74ca"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AreaComum", b =>
                {
                    b.HasOne("Domain.Entities.Condominio", "Condominio")
                        .WithMany()
                        .HasForeignKey("Id_condominio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("Domain.Entities.Arquivo", b =>
                {
                    b.HasOne("Domain.Entities.Condominio", "Condominio")
                        .WithMany()
                        .HasForeignKey("Id_condominio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("Domain.Entities.Informacao", b =>
                {
                    b.HasOne("Domain.Entities.Condominio", "Condominio")
                        .WithMany()
                        .HasForeignKey("Id_condominio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("Domain.Entities.LivroCaixa", b =>
                {
                    b.HasOne("Domain.Entities.Condominio", "Condominio")
                        .WithMany()
                        .HasForeignKey("Id_condominio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("Domain.Entities.Message", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Multa", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Ocorrencia", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Reserva", b =>
                {
                    b.HasOne("Domain.Entities.AreaComum", "AreaComum")
                        .WithMany()
                        .HasForeignKey("Id_AreaComum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaComum");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.TaxaMensal", b =>
                {
                    b.HasOne("Domain.Entities.Condominio", "Condominio")
                        .WithMany()
                        .HasForeignKey("Id_condominio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUserIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Condominio", "Condominio")
                        .WithMany()
                        .HasForeignKey("Id_condominio");

                    b.Navigation("Condominio");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Votacao", b =>
                {
                    b.HasOne("Domain.Entities.Condominio", "Condominio")
                        .WithMany()
                        .HasForeignKey("Id_condominio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("Domain.Entities.Voto", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Votacao", "Votacao")
                        .WithMany()
                        .HasForeignKey("Id_votacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Votacao");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
